LOCAL_PATH := $(call my-dir)

ifeq ($(BOARD_HAS_EMMC_BOOT_CONFIG),true)

include $(CLEAR_VARS)

LOCAL_PRELINK_MODULE := false
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/hw
LOCAL_SHARED_LIBRARIES := liblog libcutils
LOCAL_SRC_FILES := emmc_misc.c
LOCAL_MODULE := emmc_misc.$(TARGET_BOARD_PLATFORM)
LOCAL_MODULE_TAGS := eng
include $(BUILD_SHARED_LIBRARY)

endif
